users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('login-page/', views.login_page, name = "login_page"),
    path('registration-page/', views.registration_page, name = "registration_page"),
    path('login/', views.login_view, name = "login"),
    path('register/', views.register_view, name = "register"),
    path('logout/', views.logout_view, name = "logout"),
    path('test/', views.test_view, name = "test"),
    path('added-videos/', views.added_videos, name = "added_videos"),
    path("dashboard/", views.dashboard_view, name = "dashboard")
]

video/urls.py
from django.urls import path, include
from . import views

app_name = 'video'
urlpatterns = [
    path('add-video/', views.add_video, name = "add_video"),
    path('video-details/<int:id>/', views.video_details, name = "video_details"),
    path('like-video/<str:id>/', views.like_video, name = "like_video"),
    path('dislike-video/<str:id>/', views.dislike_video, name = "dislike_video"),
]

video_sharing_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('video/', include('video.urls')),
    path('', index, name="homepage"),

]

users/models.py
from enum import unique
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinLengthValidator
from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length = 255, unique = True)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    # password = models.CharField(validators=[
    #         MinLengthValidator(8, 'the field must contain at least 8 characters')
    #         ], max_length = 255)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth import authenticate, login, logout
import sweetify
from video.models import Video
# Create your views here.

def login_page(request):
    return render(request, "login_page.html")

def registration_page(request):
    return render(request, "registration.html")

def login_view(request):
    if request.method == "POST":
        email = request.POST['email']
        queryset = User.objects.get(email = email)
        password = request.POST['password']
        if queryset:
            user = authenticate(request, email = email, password = password)
            if user is not None:
                login(request,user)
                sweetify.success(request, 'Login successful')
                return redirect("users:dashboard")
            else:
                sweetify.error(request, "email and password doesn't match!", persistent=':(')
                return render(request, "login_page.html")
    return render(request, "login_page.html")

def register_view(request):
    if request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        password = request.POST["password"]
        try:
            queryset = User.objects.get(email = email)
        except:
            queryset = None
        if queryset is None:
            try:
                user = User.objects.create(first_name = first_name, last_name = last_name, email = email, password = password)
                sweetify.success(request, 'Registration successful')
                return render(request, "login_page.html")
            except Exception as e:
                sweetify.error(request, f"{e.args[0]}", persistent=':(')
                return render(request, "registration.html")
        else:
            sweetify.error(request, "Email already exists", persistent=':(')
            return render(request, "registration.html")

    return render(request, "registration.html")

def logout_view(request):
    logout(request)
    return render(request, 'login_page.html')


def dashboard_view(request):
    return render(request, "user_dashboard.html")

def added_videos(request):
    try:
        print(request.user)
        queryset = Video.objects.filter(added_by = request.user)
        print(queryset)
    except:
        queryset = None
        print(queryset)
    return render(request, "added_video_list.html", {"videos":queryset})

    
def test_view(request):
    sweetify.success(request, 'You did it', text='Good job! You successfully showed a SweetAlert message', persistent='Hell yeah')
    return redirect('/')
                
                

    

            

users/templates/added_video_list.html
{% extends 'base.html' %}
{% block title %}
Video Sharing Platform
{% endblock %}
{% block content %}

<body>
    
    <div class="container-fluid pb-video-container">
        <div class="col-md-10 offset-md-1">
            <h3 class="text-xs-center">My Videos</h3>
            <div class="row pb-row">

                {% for video in videos %}
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="{{video.url}}" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">{{ video.title }} aaaaaaaaaa</label>
                </div>
                {% empty %}
                <p class="text-center">There is no added video!</p>
                {% endfor %}

                <!-- <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/wjT2JVlUFY4?list=RDzuAcaBkcYGE?ecver=1" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">Manuel Riva - Mhm Mhm</label>
                </div>
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame " width="100%" height="230" src="https://www.youtube.com/embed/papuvlVeZg8?list=RDzuAcaBkcYGE?ecver=1" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">Clean Bandit - Rockabye</label>
                </div>
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/Y1_VsyLAGuk?list=RDzuAcaBkcYGE?ecver=1" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">Burak Yeter - Tuesday</label>
                </div> -->
            </div> 
            <!-- <div class="row pb-row">
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/3eLcD7JqOfs" frameborder="0" allowfullscreen></iframe> 
                    <label class="form-control label-warning text-xs-center">Is this the next big thing?</label>
                </div>
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/QpbQ4I3Eidg?ecver=1" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">Machine Gun - Bad Things</label>
                </div>
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/3CPBQaU8iUo" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">NEW Logitech G502 X Plus Mouse is Here!</label>
                </div>
                <div class="col-md-3 pb-video">
                    <iframe class="pb-video-frame" width="100%" height="230" src="https://www.youtube.com/embed/3CPBQaU8iUo" frameborder="0" allowfullscreen></iframe>
                    <label class="form-control label-warning text-xs-center">NEW Logitech G502 X Plus Mouse is Here!</label>
                </div>
            </div> -->
        </div>
    </div>
    
    <style>
        .pb-video-container {
            padding-top: 20px;
            background: #bdc3c7;
            font-family: Lato;
        }
    
        .pb-video {
            border: 1px solid #e6e6e6;
            padding: 5px;
        }
    
            .pb-video:hover {
                background: #2c3e50;
            }
    
        .pb-video-frame {
            transition: width 2s, height 2s;
        }
    
            .pb-video-frame:hover {
                height: 300px;
            }
    
        .pb-row {
            margin-bottom: 10px;
        }
    </style>
    
</body>

{% endblock %}

users/templates/login_page.html
<!-- Pills navs -->
{% extends "base.html"%}
{% block content %}
<!-- Pills navs -->

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">

  <div class="card card0 border-0">
      <div class="row d-flex">
          <div class="col-lg-6">
              <div class="card1 pb-5">
                  <!-- <div class="row">
                      <img src="https://i.imgur.com/CXQmsmF.png" class="logo">
                  </div> -->
                  <div class="row px-3 justify-content-center mt-4 mb-5 border-line">
                      <img src="https://i.imgur.com/uNGdWHi.png" class="image">
                  </div>
              </div>
          </div>
          <div class="col-lg-6">
              <div class="card2 card border-0 px-4 py-5">
                <form method="POST" action="{% url 'users:login' %}">
                    {% csrf_token %}
                    <div class="row px-3">
                        <label class="mb-1"><h6 class="mb-0 text-sm">Email Address</h6></label>
                        <input class="mb-4" type="text" name="email" placeholder="Enter a valid email address">
                    </div>
                    <div class="row px-3">
                        <label class="mb-1"><h6 class="mb-0 text-sm">Password</h6></label>
                        <input type="password" name="password" placeholder="Enter password">
                    </div>
                    <div class="row px-3 mb-4">
                        <div class="custom-control custom-checkbox custom-control-inline">
                            <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> 
                            <label for="chk1" class="custom-control-label text-sm">Remember me</label>
                        </div>
                        <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                    </div>
                    <div class="row mb-3 px-3">
                        <button type="submit" class="btn btn-blue text-center">Login</button>
                    </div>
                    <div class="row mb-4 px-3">
                        <small class="font-weight-bold">Don't have an account? <a class="text-danger ">Register</a></small>
                    </div>
                </form>
              </div>
          </div>
      </div>
      <div class="bg-blue py-4">
          <div class="row px-3">
              <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
              <div class="social-contact ml-4 ml-sm-auto">
                  <span class="fa fa-facebook mr-4 text-sm"></span>
                  <span class="fa fa-google-plus mr-4 text-sm"></span>
                  <span class="fa fa-linkedin mr-4 text-sm"></span>
                  <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span>
              </div>
          </div>
      </div>
  </div>
</div>
<style>
  body {
    color: #000;
    overflow-x: hidden;
    height: 100%;
    background-color: #B0BEC5;
    background-repeat: no-repeat;
}

.card0 {
    box-shadow: 0px 4px 8px 0px #757575;
    border-radius: 0px;
}

.card2 {
    margin: 0px 40px;
}

.logo {
    width: 200px;
    height: 100px;
    margin-top: 20px;
    margin-left: 35px;
}

.image {
    width: 360px;
    height: 280px;
}

.border-line {
    border-right: 1px solid #EEEEEE;
}

.facebook {
    background-color: #3b5998;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer;
}

.twitter {
    background-color: #1DA1F2;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer;
}

.linkedin {
    background-color: #2867B2;
    color: #fff;
    font-size: 18px;
    padding-top: 5px;
    border-radius: 50%;
    width: 35px;
    height: 35px;
    cursor: pointer;
}

.line {
    height: 1px;
    width: 45%;
    background-color: #E0E0E0;
    margin-top: 10px;
}

.or {
    width: 10%;
    font-weight: bold;
}

.text-sm {
    font-size: 14px !important;
}

::placeholder {
    color: #BDBDBD;
    opacity: 1;
    font-weight: 300
}

:-ms-input-placeholder {
    color: #BDBDBD;
    font-weight: 300
}

::-ms-input-placeholder {
    color: #BDBDBD;
    font-weight: 300
}

input, textarea {
    padding: 10px 12px 10px 12px;
    border: 1px solid lightgrey;
    border-radius: 2px;
    margin-bottom: 5px;
    margin-top: 2px;
    width: 100%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 14px;
    letter-spacing: 1px;
}

input:focus, textarea:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    border: 1px solid #304FFE;
    outline-width: 0;
}

button:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    outline-width: 0;
}

a {
    color: inherit;
    cursor: pointer;
}

.btn-blue {
    background-color: #1A237E;
    width: 150px;
    color: #fff;
    border-radius: 2px;
}

.btn-blue:hover {
    background-color: #000;
    cursor: pointer;
}

.bg-blue {
    color: #fff;
    background-color: #1A237E;
}

@media screen and (max-width: 991px) {
    .logo {
        margin-left: 0px;
    }

    .image {
        width: 300px;
        height: 220px;
    }

    .border-line {
        border-right: none;
    }

    .card2 {
        border-top: 1px solid #EEEEEE !important;
        margin: 0px 15px;
    }
}
</style>
<!-- Pills content -->

{% endblock %}

users/templates/registration.html
<!-- Pills navs -->
{% extends "base.html"%}
{% block content %}
<!-- Pills navs -->
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-lg-9 col-xl-7">
          <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
              <form method="POST" action="{% url 'users:register'%}">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-6 mb-4">
  
                    <div class="form-outline">
                      <input type="text" name="first_name" id="firstName" class="form-control form-control-lg" />
                      <label class="form-label" for="firstName">First Name</label>
                    </div>
  
                  </div>
                  <div class="col-md-6 mb-4">
  
                    <div class="form-outline">
                      <input type="text" name="last_name" id="lastName" class="form-control form-control-lg" />
                      <label class="form-label" for="lastName">Last Name</label>
                    </div>
  
                  </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-4 pb-2">
    
                      <div class="form-outline">
                        <input type="password" name="password" id="password" class="form-control form-control-lg" />
                        <label class="form-label" for="emailAddress">Password</label>
                      </div>
    
                    </div>

                    <div class="col-md-6 mb-4 pb-2">
  
                        <div class="form-outline">
                          <input type="email" name="email" id="emailAddress" class="form-control form-control-lg" />
                          <label class="form-label" for="emailAddress">Email</label>
                        </div>
      
                      </div>
                      
                    
                  </div>
  
                
  
                <div class="mt-4 pt-2">
                  <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                </div>
  
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <style>
    .gradient-custom {
/* fallback for old browsers */
background: #f093fb;

/* Chrome 10-25, Safari 5.1-6 */
background: -webkit-linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1));

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
background: linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1))
}

.card-registration .select-input.form-control[readonly]:not([disabled]) {
font-size: 1rem;
line-height: 2.15;
padding-left: .75em;
padding-right: .75em;
}
.card-registration .select-arrow {
top: 13px;
}
  </style>
{% endblock %}

users/templates/user_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-5">
     <h1>Please enter the title and embded url to add video</h1>
     <form accept-charset="UTF-8" action="{% url 'video:add_video'%}" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
       <div class="form-group">
         <label for="title">Title</label>
         <input type="text" name="title" class="form-control" id="title" placeholder="Enter video title" required="required">
       </div>
       <div class="form-group">
         <label for="url" required="required">Video url</label>
         <input type="url" name="url" class="form-control" id="url" aria-describedby="emailHelp" placeholder="Enter video url">
       </div>
       <hr>
       <button type="submit" class="btn btn-primary">Submit</button>
     </form>
 </div> 
{% endblock %}