users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('login-page/', views.login_page, name = "login_page"),
    path('registration-page/', views.registration_page, name = "registration_page"),
    path('login/', views.login_view, name = "login"),
    path('register/', views.register_view, name = "register"),
    path('logout/', views.logout_view, name = "logout"),
    path('test/', views.test_view, name = "test"),
    path('added-videos/', views.added_videos, name = "added_videos"),
    path("dashboard/", views.dashboard_view, name = "dashboard")
]

video/urls.py
from django.urls import path, include
from . import views

app_name = 'video'
urlpatterns = [
    path('add-video/', views.add_video, name = "add_video"),
    path('video-details/<int:id>/', views.video_details, name = "video_details"),
    path('like-video/<str:id>/', views.like_video, name = "like_video"),
    path('dislike-video/<str:id>/', views.dislike_video, name = "dislike_video"),
]

video_sharing_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('video/', include('video.urls')),
    path('', index, name="homepage"),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <title>Document</title>
    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:added_videos' %}">Added videos</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>

            
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login_page' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:registration_page' %}">Register</a>
          </li>
            {% endif %}
            
          </ul>
        </div>
      </nav>
{% load sweetify %}
{% sweetify %}
</body>
</html>

{% block content %}
{% endblock %}

templates/list.html
{% extends 'base.html' %} 
{% load embed_video_tags %}
{% block title %}
Video Sharing Platform
{% endblock %}
{% block content %}

<body>
    
    <div class="container-fluid pb-video-container">
        <div class="col-md-10 offset-md-1">
            <h3 class="text-xs-center">Videos</h3>
            <div class="row pb-row ">
                {% for video in videos %}
                <div class="col-md-3 pb-video mb-2">
                    <div class="vid-div">
                        {% video video.embded_video '380x315' %}
                    </div>                    
                    <label class="form-control label-warning text-xs-center">{{ video.title }}</label>
                    <div class="d-flex justify-content-center">
                        <div class="details-div mt-1 mr-4">
                            <a type="submit" class="btn btn-primary" data-toggle="modal" data-target="#videodetails_{{video.id}}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                        </div>
                        <div class="like-div mr-4">
                            {% if request.user in video.like.user.all %}
                            <a name="{{ video.id }}_like" vid-modal-id="{{video.id}}" data-url="{% url 'video:like_video' video.id %}" style="font-size:30px;color: blue;" class="liking" id="co"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                            </a>
                            <span class="like-no" style="font-size:30px;"> {{ video.like.user.count }} </span>
                    
                            {% else %}
                            <a name="{{ video.id }}_like" vid-modal-id="{{video.id}}" data-url="{% url 'video:like_video' video.id %}" style="font-size:30px;color: black;" class="liking" id="co"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                            </a>
                            <span class="like-no" style="font-size:30px;"> {{ video.like.user.count }} </span>                            
                        
                        {% endif %}
                        </div>
                        <div class="dislike-div mr-4">
                            {% if request.user in video.dislike.user.all %}
                            <a name="{{ video.id }}_dislike" vid-modal-id="{{video.id}}" data-url="{% url 'video:dislike_video' video.id %}" style="font-size:30px;color: blue;" class="disliking" id="co-1"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
                            <span class="dislike-no" style="font-size:30px;"> {{ video.dislike.user.count }} </span>
                            
                        {% else %}
                        <a name="{{ video.id }}_dislike" vid-modal-id="{{video.id}}" data-url="{% url 'video:dislike_video' video.id %}" style="font-size:30px;color: black;" class="disliking" id="co-1"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
                        <span class="dislike-no" style="font-size:30px;"> {{ video.dislike.user.count }} </span>
                            
                        {% endif %}
                        </div>
                    </div>
                    
                    
                    <div class="modal fade" id="videodetails_{{video.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">View details</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-6 mb-4">
                    
                                        <h5>Added By: {{ video.added_by.first_name }}</h5>
                    
                                    </div>
                    
                                        <div class="col-md-6 mb-4">
                
                                            <h5>Added At: {{ video.created_at }}</h5>
                        
                                        </div>
                    
                                </div>
                                <div class="row">
                                    <div  class="col-md-6 mb-4">
                                        <h5 id="like-count-{{video.id}}">Like Count: {{ video.get_total_likes }}</h5>
                                    </div>
                
                                    <div  class="col-md-6 mb-4">
                                        <h5 id="dislike-count-{{video.id}}">Dislike Count: {{ video.get_total_dislikes }}</h5>
                                    </div>
                    
                                </div>

                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <h5>liked by: </h5>
                                        {% for usr in video.like.user.all %}
                                        {{ usr }}
                                        {% endfor %}
                                    </div>
                
                                    <div class="col-md-6 mb-4">
                                        <h5>Disliked by: </h5>
                                        {% for usr in video.dislike.user.all %}
                                        {{ usr }}
                                        {% endfor %}
                                    </div>
                    
                                </div>


                                
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                        </div>
                    </div>                    
                </div>
                {% empty %}
                <h3 >Sorry no video found</h3>
                {% endfor %}
            </div> 
        </div>
    </div>

    
    
    <style>
        .pb-video-container {
            padding-top: 20px;
            background: #bdc3c7;
            font-family: Lato;
        }
    
        .pb-video {
            border: 1px solid #e6e6e6;
            padding: 5px;
        }
    
            .pb-video:hover {
                background: #e6e6e6;
            }
    
        .pb-video-frame {
            transition: width 2s, height 2s;
        }
    
            .pb-video-frame:hover {
                height: 300px;
            }
    
        .pb-row {
            margin-bottom: 10px;
        }
    </style>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
// Like AJAX CALL
$('.liking').click(function(){
    let vidId = $(this).attr('vid-modal-id');
    let likedVidId = `like-count-${vidId}`;
    let dislikedVidId = `dislike-count-${vidId}`;
    let url = $(this).attr('data-url');
    let loginUrl = "{% url 'users:login' %}";
    
    $.ajax({
            type: "POST",
            url: url,
            data: {'video_id': $(this).attr('name'),'operation':'like_submit','csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response) {
                console.log(response);
                if (response.is_logged_in == true) {
                    selector = document.getElementsByName(response.video_id);
                    dislike_selector = document.getElementsByName(response.disliked_video_id);
                    
                    if(response.liked==true){
                        $(selector).css("color","blue");
                        $(selector).siblings("span.like-no").html(response.like_count);
                        $(dislike_selector).css("color","black");
                        $(dislike_selector).siblings("span.dislike-no").html(response.dislike_count);
                        document.getElementById(likedVidId).innerHTML = `Like Count: ${response.like_count}`;
                        document.getElementById(dislikedVidId).innerHTML = `Dislike Count: ${response.dislike_count}`;

                    }
                    else if(response.liked==false){
                        $(selector).css("color","black");
                        $(selector).siblings("span.like-no").html(response.like_count);
                        $(dislike_selector).css("color","black");
                        $(dislike_selector).siblings("span.dislike-no").html(response.dislike_count);
                        document.getElementById(likedVidId).innerHTML = `Like Count: ${response.like_count}`;
                        document.getElementById(dislikedVidId).innerHTML = `Dislike Count: ${response.dislike_count}`;


                        

                    }
                }
                else {
                    alert("You need to login first to like or dislike")
                    location.href = loginUrl;
                }
                

                },
            error: function (error){
                console.log(error);
        },
        
        });

  })
</script>

<script>
    //Dislike AJAX CALL
    $('.disliking').click(function(){
        let vidId = $(this).attr('vid-modal-id');
        let likedVidId = `like-count-${vidId}`;
        let dislikedVidId = `dislike-count-${vidId}`;
        let url = $(this).attr('data-url');
        let loginUrl = "{% url 'users:login' %}";
        console.log("dddd",$(this).attr('name'));
        console.log(url);
        $.ajax({
                type: "POST",
                url: url,
                data: {'video_id': $(this).attr('name'),'operation':'dislike_submit','csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json",
                success: function(response) {
                    console.log(response);
                    if (response.is_logged_in == true) {
                        selector = document.getElementsByName(response.video_id);
                        like_selector = document.getElementsByName(response.liked_video_id);
                        if(response.disliked==true){
                            $(selector).css("color","blue");
                            $(selector).siblings("span.dislike-no").html(response.dislike_count);
                            $(like_selector).css("color","black");
                            $(like_selector).siblings("span.like-no").html(response.like_count);
                            document.getElementById(likedVidId).innerHTML = `Like Count: ${response.like_count}`;
                            document.getElementById(dislikedVidId).innerHTML = `Dislike Count: ${response.dislike_count}`;


                        }
                        else if(response.disliked==false){
                            $(selector).css("color","black");
                            $(selector).siblings("span.dislike-no").html(response.dislike_count);
                            $(like_selector).css("color","black");
                            $(like_selector).siblings("span.like-no").html(response.like_count);
                            document.getElementById(dislikedVidId).innerHTML = `Dislike Count: ${response.dislike_count}`;
                            document.getElementById(likedVidId).innerHTML = `Like Count: ${response.like_count}`;



                        }
                    }
                    else {
                    alert("You need to login first to like or dislike")
                    location.href = loginUrl;
                }
    
                    },
                error: function (error){
                    console.log(error);
            },
            
            });
    
      })
</script>
</body>


{% endblock %}